services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  streamlit:
    build: rag-application/.
    container_name: streamlit
    ports:
      - 8501:8501
    environment:
      PINECONE_API_KEY: "<PINECONE_API_KEY>" # edit
      PINECONE_HOST: "<PINECONE_HOST>"  # edit
      OPENAI_API_KEY: "<OPENAI_API_KEY>" # edit
