spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: pgadmin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
